# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-31 13:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('time', models.DateTimeField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_message', to=settings.AUTH_USER_MODEL)),
                ('receiver', models.ManyToManyField(related_name='received_message', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
